[package]
name = "shadowdark-mkchar"
version = "1.0.1"
edition = "2024"

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
rand = "0.9.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
strum = "0.27.1"
strum_macros = "0.27.1"
typst = "0.13.1"
